version: "3"

services:
  one:
    build: appone
    mem_limit: 350m
    ports:
      - "8081:8080"
    depends_on:
      - kafka
  two:
    build: apptwo
    mem_limit: 350m
    depends_on:
      - kafka
  three:
    build: appthree
    mem_limit: 350m
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "one-fail:1:1, two-fail:1:1, three-fail:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock